name: inboxer2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  #receive_sharing_intent: ^1.4.5
  receive_sharing_intent: 
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
  path: 
  file_picker: ^10.3.2
  shared_preferences: ^2.2.3
  get_it: ^8.2.0
  watch_it: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path : "assets/icon/icons8-trash-24.png"
